### ISSUE TITLE
README for each project

### ISSUE THREAD

**Issue by rolandbaer** [rolandbaer/embedded#3]
A short description based on the german blog articles should be added to each project.

- [x] read_dht_01 --> https://blog.rolandbaer.ch/2020/03/07/temperatur-und-luftfeuchtigkeit-messen-mit-dem-arduino-nano/ --> see PR #4
- [x] read_dht_02 --> https://blog.rolandbaer.ch/2020/03/23/temperatur-und-luftfeuchtigkeit-messen-und-anzeigen-mit-dem-arduino-nano/ --> see PR #5
- [x] buttons_1 --> https://blog.rolandbaer.ch/2020/03/29/erste-schritte-mit-dem-wemos-d1-mini/ --> see PR #6 
- [x]  dht_webserver --> https://blog.rolandbaer.ch/2020/03/30/wemos-d1-mini-als-temperatur-und-luftfeuchtigkeits-webserver/ --> see PR #8 

projects without blog article:
- [x] ~~buttons_and_dht_1~~ --> deleted
- [x] state_machine_1 --> see PR #9
- [x] window_controller --> see PR #10
